### ISSUE TITLE
Unit for pconc

### ISSUE THREAD

**Issue by AJO5** [simonom/PyCHAM#18]
Hi Simon, 

According to the model variable description, the unit for pconc is # particles/cc (air). Using SMPS data, does this refer to the total number concentration (dN) for each size bin, or the density spectral (dN/dLogDp)?

I was also wondering about the following model variable:
https://github.com/simonom/PyCHAM/blob/master/PyCHAM/output/example_scheme_inc_aq/Example_Run_Output_inc_aq/inputs/example_model_var_inc_aq.txt

It contains these variables:
number_size_bins = 8
pconct = 0.
pconc = 1.e4
mean_rad = 1.e-1

Does 1.e4 in pconc refer to the total particle concentration across all eight size bins or does it refer to the first mode of the particle size (since the mean_rad is provided)?

Thank you!

Aldrian Jerriko
Undergraduate student at National University of Singapore

**Comment by simonom** [comment]
Thanks for getting in touch Aldrian,

It refers to dN

It is the total for that mode which will be spread across the 8 size bins.

We seem to have a bug affecting water partitioning to seed particles, so if you think this will affect your work, please wait for the next release (hopefully this week).

Kind regards,
Simon

National Centre for Atmospheric Science Postdoctoral Research Associate

From: AJO5 ***@***.***>
Sent: 26 July 2021 18:43
To: simonom/PyCHAM ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [simonom/PyCHAM] Unit for pconc (#18)


Hi Simon,

According to the model variable description, the unit for pconc is # particles/cc (air). Using SMPS data, does this refer to the total number concentration (dN) for each size bin, or the density spectral (dN/dLogDp)?

I was also wondering about the following model variable:
https://github.com/simonom/PyCHAM/blob/master/PyCHAM/output/example_scheme_inc_aq/Example_Run_Output_inc_aq/inputs/example_model_var_inc_aq.txt

It contains these variables:
number_size_bins = 8
pconct = 0.
pconc = 1.e4
mean_rad = 1.e-1

Does 1.e4 in pconc refer to the total particle concentration across all eight size bins or does it refer to the first mode of the particle size (since the mean_rad is provided)?

Thank you!

Aldrian Jerriko
Undergraduate student at National University of Singapore

**Comment by AJO5** [comment]
Thanks a lot for your feedback!

**Comment by simonom** [comment]
Hello,

The bug previously mentioned has been resolved in the latest version of PyCHAM, available now on GitHub.

Kind regards,
Simon

National Centre for Atmospheric Science Postdoctoral Research Associate
