### ISSUE TITLE
About the efficiency of PyCHAM

### ISSUE THREAD

**Issue by kasal2010** [simonom/PyCHAM#24]
Dear Simon,

I am a beginner of PyCHAM, and today I tried the cases under ...\input\outdoor_win_hp. My platform is windows 11, AMD Ryzen 7 5800HS with 16GB memory. First, I directly run the cases, and found that it takes a long time to run. Then I adjust the total_model_time and the integration step into 10800s and 3600s, respectively, and found the total runtime is about 15min. Is there any way to increase the efficiency?

Best regards!

Kun

**Comment by simonom** [comment]
Dear Kun,

Thank you for messaging.

You could try decreasing the absolute and relative integration tolerances, which are described in the README. However, there is a risk that you lose accuracy doing this. The runtime you state is reasonable for this simulation, which uses the entire Master Chemical Mechanism for the chemical scheme. Another aspect to consider is do you require this much chemical detail, or would a smaller chemical scheme suffice?

Thanks,
Simon

**Comment by kasal2010** [comment]
Dear Simon,

Thanks for your reply. I may try some reduced mechanism after. BTW, is there any tool available to generate .kqq (or .eqn) and .xml file from a given mechanism (like SAPRC.fac)?

Best regards!

Kun

**Comment by simonom** [comment]
Good question,

In theory, PyCHAM should cope with any chemical scheme, so long as it is told the formatting for that scheme using the user-defined chem_scheme_markers variable. However, I have not tested this for something like SAPRC.fac, and I would like to, therefore can you send me the file?

In terms of the xml file, this provides the chemical structure (via SMILES strings) of each molecule so that physical properties such as vapour pressure can be estimated. If you don’t need these physical properties (vapour pressure, density, diffusion coefficient), then let me know so I can code in a bypass. If you need these physical properties, then unfortunately I don’t know of tools to create the SMILES strings, however the makers of the chemical scheme may.

Kind regards,
Simon O'Meara (He)
National Centre for Atmospheric Science



On 29 Mar 2024, at 00:48, kasal2010 ***@***.***> wrote:


Dear Simon,

Thanks for your reply. I may try some reduced mechanism after. BTW, is there any tool available to generate .kqq (or .eqn) and .xml file from a given mechanism (like SAPRC.fac)?

Best regards!

Kun

**Comment by kasal2010** [comment]
Dear Simon,

Thanks for your reply! Please find enclosed the SAPRC22 mechanism and its supplemental file, which are downloaded from the website of SAPRC (SAPRC Atmospheric Chemical Mechanisms and VOC Reactivity Scales (ucr.edu)<https://intra.engr.ucr.edu/~carter/SAPRC/>). If I’d like to simulate SOA formation with this mechanism, according to the introduction of PyCHAM, would the following steps be done before I run the model?

  1.  Convert the mechanism file into the type that can be identified by PyCHAM
  2.  Generate xml file according to the MechGen structure in the supplemental file.
  3.
Best regards!

Kun
