### ISSUE TITLE
Improve installation instructions

### ISSUE THREAD

**Issue by dhhagan** [simonom/PyCHAM#6]
At this moment, the installation instructions are a bit convoluted. It would be great if you could:

  1. provide links to the non-python packages that are required for installation
  2. include all necessary instructions on this page so that users don't have to navigate multiple other sites
  3. add instructions for installing Sundials and openbabel for different platforms. It looks like sundials is available on [homebrew][1] for macOS. The same looks to be true for [open-babel][2].

I will go ahead and add these instructions and send a PR as part of the review process for [JOSS][3].

[1]: https://formulae.brew.sh/formula/sundials
[2]: https://formulae.brew.sh/formula/open-babel
[3]: https://github.com/openjournals/joss-reviews/issues/1918

**Comment by simonom** [comment]
Hi @dhhagan , I have looked into this, as well as the Assimulo dependencies you mentioned (with regard to Sundials and python version).  The Assimulo package represents a bottleneck it seems in terms of install options.  Trying to install Assimulo from source fails in my experience (due to missing files in Assimulo), but works smoothly using the conda installation described in the PyCHAM README.  I suggest that the 'pip Install' section be removed from the README, leaving only the 'conda Install' section.  Would this satisfy the review?

**Comment by dhhagan** [comment]
Yup - that works. I would still throw it in as a requirement, as I was able to install pyCHAM directly and it didn't throw an error until runtime.

**Comment by simonom** [comment]
Actually, I've found a way to install from source.  So I'll update the instructions today.
